<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gap Analysis Report — GRC Charter</title>
    @include('reports._partials._styles')
    <style>
        /* Page-specific: KPI flex (gap-analysis uses flex layout, not table) */
        .kpi-flex { display: flex; gap: 12px; margin-bottom: 20px; }
        .kpi-flex .kpi-box {
            flex: 1;
            border: 1px solid #d9d9dd;
            border-radius: 6px;
            padding: 12px 14px;
            text-align: center;
            background: #fafaf8;
        }
        .kpi-flex .kpi-value { font-size: 22px; font-weight: bold; color: inherit; }
        .kpi-flex .kpi-label { font-size: 9px; color: #75758a; margin-top: 2px; text-transform: uppercase; letter-spacing: 0.5px; }

        /* Risk rating colours */
        .rating-critical { color: #e5484d; }
        .rating-high     { color: #f76b15; }
        .rating-medium   { color: #f5b929; }
        .rating-low      { color: #46bd5f; }

        /* Narrative paragraphs (gap-analysis doesn't use a tinted block — plain text) */
        .narrative-plain p { margin-bottom: 10px; text-align: justify; }

        /* Action-list rows (left-bordered) */
        .action-item {
            padding: 8px 12px;
            border-left: 3px solid #d9d9dd;
            margin-bottom: 8px;
            background: #fafaf8;
        }
        .action-item.high   { border-left-color: #e5484d; }
        .action-item.medium { border-left-color: #f5b929; }
        .action-item.low    { border-left-color: #46bd5f; }
        .action-title { font-weight: bold; font-size: 10px; }
        .action-meta  { font-size: 9px; color: #75758a; margin-top: 3px; }

        /* Positive highlights */
        .highlight-item {
            padding: 6px 10px;
            border-left: 3px solid #46bd5f;
            margin-bottom: 6px;
            background: #ecf9ef;
            font-size: 10px;
        }
    </style>
</head>
<body>

@include('reports._partials._header', [
    'title'    => 'AI-Powered Gap Analysis Report',
    'subtitle' => 'Compliance gap findings, remediation recommendations, and prioritised action list',
    'meta'     => 'Generated: ' . $generatedAt . '   |   Classification: Internal',
])
<div class="ai-badge-strip">
    &#9889; This gap analysis narrative was generated by AI (Claude Sonnet) based on live GRC system data.
    Findings should be reviewed and validated by a qualified compliance officer before use in formal reporting.
</div>

<div class="content">

    <!-- ── KPI Row ── -->
    @php
        $ratingClass = match(strtolower($result['overall_risk_rating'] ?? '')) {
            'critical' => 'rating-critical',
            'high'     => 'rating-high',
            'medium'   => 'rating-medium',
            default    => 'rating-low',
        };
    @endphp

    <div class="kpi-flex">
        <div class="kpi-box">
            <div class="kpi-value">{{ $compliancePct }}%</div>
            <div class="kpi-label">Self-Assessed Compliance</div>
        </div>
        <div class="kpi-box">
            <div class="kpi-value" style="color: #e5484d;">{{ $gapSummary['non_compliant'] }}</div>
            <div class="kpi-label">Non-Compliant Controls</div>
        </div>
        <div class="kpi-box">
            <div class="kpi-value" style="color: #f5b929;">{{ $gapSummary['partially_compliant'] }}</div>
            <div class="kpi-label">Partially Compliant</div>
        </div>
        <div class="kpi-box">
            <div class="kpi-value {{ $ratingClass }}">{{ $result['overall_risk_rating'] ?? 'N/A' }}</div>
            <div class="kpi-label">Overall Risk Rating</div>
        </div>
    </div>

    <!-- ── Executive Summary ── -->
    <div class="section" style="padding:0;">
        <div class="section-title">Executive Summary</div>
        <div class="narrative-plain">
            @foreach(array_filter(preg_split('/\n{2,}/', trim($result['executive_summary'] ?? ''))) as $para)
                <p>{{ $para }}</p>
            @endforeach
        </div>
    </div>

    <!-- ── Critical Gaps ── -->
    @if(!empty($result['critical_gaps']))
    <div class="section" style="padding:0;">
        <div class="section-title">Critical Gaps Requiring Immediate Attention</div>
        <table>
            <thead>
                <tr>
                    <th style="width:10%">Control ID</th>
                    <th style="width:10%">Framework</th>
                    <th style="width:25%">Control Title</th>
                    <th style="width:30%">Finding</th>
                    <th style="width:25%">Recommendation</th>
                </tr>
            </thead>
            <tbody>
                @foreach($result['critical_gaps'] as $gap)
                <tr>
                    <td><strong>{{ $gap['control_id'] ?? '—' }}</strong></td>
                    <td>{{ $gap['framework'] ?? '—' }}</td>
                    <td>{{ $gap['title'] ?? '—' }}</td>
                    <td>{{ $gap['finding'] ?? '—' }}</td>
                    <td>{{ $gap['recommendation'] ?? '—' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <!-- ── Category Analysis ── -->
    @if(!empty($result['category_analysis']))
    <div class="section" style="padding:0;">
        <div class="section-title">Per-Category Gap Analysis</div>
        <table>
            <thead>
                <tr>
                    <th style="width:22%">Category</th>
                    <th style="width:10%">Non-Compliant</th>
                    <th style="width:10%">Partial</th>
                    <th style="width:58%">Summary</th>
                </tr>
            </thead>
            <tbody>
                @foreach($result['category_analysis'] as $cat)
                <tr>
                    <td><strong>{{ $cat['category'] ?? '—' }}</strong></td>
                    <td><span class="badge badge-nc">{{ $cat['gap_count'] ?? 0 }}</span></td>
                    <td><span class="badge badge-pc">{{ $cat['partial_count'] ?? 0 }}</span></td>
                    <td>{{ $cat['summary'] ?? '—' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

</div>

<div class="page-break"></div>

<div class="content">

    <!-- ── Detailed Gap Register ── -->
    <div class="section" style="padding:0;">
        <div class="section-title">Detailed Gap Register</div>
        <table>
            <thead>
                <tr>
                    <th style="width:10%">Control ID</th>
                    <th style="width:10%">Framework</th>
                    <th style="width:22%">Title</th>
                    <th style="width:15%">Category</th>
                    <th style="width:13%">Status</th>
                    <th style="width:5%">Evidence</th>
                    <th style="width:25%">Notes</th>
                </tr>
            </thead>
            <tbody>
                @forelse($gapData as $row)
                <tr>
                    <td><strong>{{ $row['control_id'] }}</strong></td>
                    <td>{{ $row['framework'] }}</td>
                    <td>{{ $row['title'] }}</td>
                    <td>{{ $row['category'] ?? '—' }}</td>
                    <td>
                        @if($row['compliance_status'] === 'non_compliant')
                            <span class="badge badge-nc">Non-Compliant</span>
                        @else
                            <span class="badge badge-pc">Partial</span>
                        @endif
                    </td>
                    <td style="text-align:center">{{ $row['evidence_count'] }}</td>
                    <td>{{ $row['notes'] ?? '—' }}</td>
                </tr>
                @empty
                <tr><td colspan="7" style="text-align:center; color: #75758a;">No gaps recorded.</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <!-- ── Prioritised Action List ── -->
    @if(!empty($result['action_list']))
    <div class="section" style="padding:0;">
        <div class="section-title">Prioritised Action List</div>
        @foreach($result['action_list'] as $action)
        @php $pClass = strtolower($action['priority'] ?? 'low'); @endphp
        <div class="action-item {{ $pClass }}">
            <div class="action-title">
                <span class="badge badge-{{ $pClass }}">{{ $action['priority'] ?? '' }}</span>
                &nbsp;{{ $action['action'] ?? '' }}
            </div>
            <div class="action-meta">
                @if(!empty($action['control_ids']))
                    Controls: {{ implode(', ', $action['control_ids']) }} &nbsp;|&nbsp;
                @endif
                Owner: {{ $action['owner'] ?? 'TBD' }}
            </div>
        </div>
        @endforeach
    </div>
    @endif

    <!-- ── Positive Highlights ── -->
    @if(!empty($result['positive_highlights']))
    <div class="section" style="padding:0;">
        <div class="section-title">Positive Highlights</div>
        @foreach($result['positive_highlights'] as $highlight)
        <div class="highlight-item">&#10003;&nbsp; {{ $highlight }}</div>
        @endforeach
    </div>
    @endif

    @include('reports._partials._footer', [
        'left'  => 'GRC Charter — Gap Analysis Report — Generated ' . $generatedAt,
        'right' => 'AI-assisted analysis — For internal use only — Validate before formal submission',
        'fixed' => false,
    ])
</div>

</body>
</html>
